package vistas.acceso;

import java.awt.Color;
import vistas.FPrincipal;
import servicios.TextPrompt;
import java.awt.Font;
import servicios.Control;

public class FAcceso extends javax.swing.JFrame {
    
    Control control = new Control();
    boolean flag = false;
    /**
     * Creates new form FAcceso
     */
    public FAcceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBG = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTextUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JPClave = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblPasswordShower = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                abrirFormularioEvento(evt);
            }
        });

        jPanelBG.setBackground(new java.awt.Color(255, 255, 255));
        jPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("INICIAR SESIÓN");
        jPanelBG.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        JTextUsuario.setBackground(new java.awt.Color(255, 255, 255));
        JTextUsuario.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        JTextUsuario.setBorder(null);
        JTextUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                controlTeclasJTEventoKeyTyped(evt);
            }
        });
        jPanelBG.add(JTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 410, 32));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CONTRASEÑA");
        jPanelBG.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("USUARIO");
        jPanelBG.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        JPClave.setBackground(new java.awt.Color(255, 255, 255));
        JPClave.setBorder(null);
        JPClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                actualizarPasswordShower(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                deshabilitarTeclasJP(evt);
            }
        });
        jPanelBG.add(JPClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 288, 420, 32));

        jLabel8.setFont(new java.awt.Font("JetBrains Mono", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("<html>\n<center><p>COBRO DE IMPUESTO</p><p>VEHICULAR</p></center>\n</html>");
        jPanelBG.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/logo.png"))); // NOI18N
        jPanelBG.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 150, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multimedia/city.png"))); // NOI18N
        jPanelBG.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, -4, 200, 500));
        jPanelBG.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 60));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBG.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 420, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanelBG.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 222, 420, 10));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("SMCI");
        jPanelBG.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAcceder(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccederDecoracionEntrarEventoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccederDecoracionSalirEventoMouseExited(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ACCEDER");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanelBG.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 140, 40));

        lblPasswordShower.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPasswordShower.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PasswordShowerEvento(evt);
            }
        });
        jPanelBG.add(lblPasswordShower, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 30, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 153, 153));
        jLabel10.setText("${PasswordShowed}");
        jPanelBG.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void abrirFormularioEvento(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_abrirFormularioEvento
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel7, "src/multimedia/coche.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblPasswordShower, "src/multimedia/seePassword.png");
        jLabel10.setText("");
        TextPrompt placeholderUser = new TextPrompt("Ingrese su cedula", JTextUsuario);
        placeholderUser.changeAlpha(0.75f);
        placeholderUser.changeStyle(Font.ITALIC);
        TextPrompt placeholderClave = new TextPrompt("Ingrese su clave", JPClave);
        placeholderClave.changeAlpha(0.75f);
        placeholderClave.changeStyle(Font.ITALIC);
    }//GEN-LAST:event_abrirFormularioEvento

    private void btnAcceder(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAcceder
        FPrincipal fprincipal = new FPrincipal();
        if(control.controlAccesoUsuario(JTextUsuario.getText().trim(), String.valueOf(JPClave.getPassword()).trim())){
            fprincipal.setPropietario(control.obtenerPropietario(JTextUsuario.getText()));
            this.setVisible(false);
            fprincipal.setVisible(true);
        }
    }//GEN-LAST:event_btnAcceder

    private void PasswordShowerEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PasswordShowerEvento
        if(flag == false){
            rsscalelabel.RSScaleLabel.setScaleLabel(lblPasswordShower, "src/multimedia/hidePassword.png");
            flag = true;
            jLabel10.setText(String.valueOf(JPClave.getPassword()).trim());
        } else {
            rsscalelabel.RSScaleLabel.setScaleLabel(lblPasswordShower, "src/multimedia/seePassword.png");
            flag = false;
            jLabel10.setText("");
        }
    }//GEN-LAST:event_PasswordShowerEvento

    private void actualizarPasswordShower(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_actualizarPasswordShower
        if(flag == true){
            jLabel10.setText(String.valueOf(JPClave.getPassword()).trim());
        }
    }//GEN-LAST:event_actualizarPasswordShower

    private void deshabilitarTeclasJP(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_deshabilitarTeclasJP
        // Deshabilita la tecla espacio para el JPasswordField
        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
    }//GEN-LAST:event_deshabilitarTeclasJP

    private void controlTeclasJTEventoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_controlTeclasJTEventoKeyTyped
        // Deshabilita la tecla espacio para el JTextFiell
        if (evt.getKeyChar() == ' ') {
            evt.consume();
        }
        
        // Limita la cantidad de caracteres ingresados a 10
        if (JTextUsuario.getText().length() >= 10) {
            evt.consume();
        }
        
        // Solo permite el ingreso de numeros
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_controlTeclasJTEventoKeyTyped

    private void btnAccederDecoracionEntrarEventoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederDecoracionEntrarEventoMouseEntered
        jPanel1.setBackground(Color.decode("#005D8B"));
    }//GEN-LAST:event_btnAccederDecoracionEntrarEventoMouseEntered

    private void btnAccederDecoracionSalirEventoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccederDecoracionSalirEventoMouseExited
        jPanel1.setBackground(Color.decode("#3399FF"));
    }//GEN-LAST:event_btnAccederDecoracionSalirEventoMouseExited

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FAcceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FAcceso().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField JPClave;
    private javax.swing.JTextField JTextUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblPasswordShower;
    // End of variables declaration//GEN-END:variables
}
