package vistas;

import vistas.menuvehiculo.DVehiculo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelos.Propietario;
import modelos.Vehiculo;
import servicios.Control;
import vistas.acceso.FAcceso;

/**
 *
 * @author josef
 */
public class FPrincipal extends javax.swing.JFrame {

    public Propietario propietario = new Propietario();
    Control control = new Control();

    /**
     * Creates new form FPrincipal
     */
    public FPrincipal() {
        initComponents();

        // Maximiza la pantalla y la ajusta
        setLocation(-10, 0);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(screenSize.width + 20, screenSize.height - 30);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCedula = new javax.swing.JLabel();
        lblLicencia = new javax.swing.JLabel();
        lblProfileIcon = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jpConfiguracion = new javax.swing.JPanel();
        lblConfigIcon = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jpVehiculo = new javax.swing.JPanel();
        lblCarIcon = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jpPago = new javax.swing.JPanel();
        lblTaxIcon = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de recaudacion de impuesto vehicular");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                AbrirFrameEvento(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 134, 190));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel2.setText("CEDULA");

        lblUsuario.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblUsuario.setText("${nombrePropietario}");

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel3.setText("USUARIO");

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabel4.setText("LICENCIA");

        lblCedula.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblCedula.setText("${Cedula}");

        lblLicencia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lblLicencia.setText("${Licencia}");

        lblProfileIcon.setText("${imgUserProfile}");

        jLabel5.setText("${PowerIcon}");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarEvento(evt);
            }
        });

        jLabel10.setText("${CloseSesion}");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel11.setText("<html>\n<center>\n<div>\nCERRAR\n</div>\n<div>\nPROGRAMA\n</div>\n</center>\n</html>");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabel12.setText("<html> <center> <div> CERRAR </div> <div>SESION </div> </center> </html>");

        jpConfiguracion.setBackground(new java.awt.Color(255, 255, 255));
        jpConfiguracion.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jpConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpConfiguracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpConfiguracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpConfiguracionHoverEvento(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpConfiguracionExitEvento(evt);
            }
        });

        lblConfigIcon.setText("${configIcon}");
        lblConfigIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel9.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        jLabel9.setText("<html> <center> <div>AJUSTES DE</div><div>USUARIO</div> </center> </html>");

        javax.swing.GroupLayout jpConfiguracionLayout = new javax.swing.GroupLayout(jpConfiguracion);
        jpConfiguracion.setLayout(jpConfiguracionLayout);
        jpConfiguracionLayout.setHorizontalGroup(
            jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpConfiguracionLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpConfiguracionLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(lblConfigIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        jpConfiguracionLayout.setVerticalGroup(
            jpConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConfigIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblUsuario)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(lblCedula))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblLicencia, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addComponent(jSeparator2)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jpConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 7, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfileIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblCedula)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblLicencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jpVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        jpVehiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jpVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVehiculoEventoClic(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpVehiculoHoverEvento(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpVehiculoExitEvento(evt);
            }
        });

        lblCarIcon.setText("${CarIcon}");
        lblCarIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel6.setText("MIS VEHICULOS");

        javax.swing.GroupLayout jpVehiculoLayout = new javax.swing.GroupLayout(jpVehiculo);
        jpVehiculo.setLayout(jpVehiculoLayout);
        jpVehiculoLayout.setHorizontalGroup(
            jpVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVehiculoLayout.createSequentialGroup()
                .addGroup(jpVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpVehiculoLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel6))
                    .addGroup(jpVehiculoLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblCarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jpVehiculoLayout.setVerticalGroup(
            jpVehiculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpVehiculoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblCarIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jpPago.setBackground(new java.awt.Color(255, 255, 255));
        jpPago.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(102, 102, 102)));
        jpPago.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jpPago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpPagoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jpPagoHoverEvento(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jpPagoExitEvento(evt);
            }
        });

        lblTaxIcon.setText("${taxIcon}");
        lblTaxIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setText("<html>\n<center><div>PAGO DE</div><div>IMPUESTO VEHICULAR</div></center>\n</html>");

        javax.swing.GroupLayout jpPagoLayout = new javax.swing.GroupLayout(jpPago);
        jpPago.setLayout(jpPagoLayout);
        jpPagoLayout.setHorizontalGroup(
            jpPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagoLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(lblTaxIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPagoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        jpPagoLayout.setVerticalGroup(
            jpPagoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPagoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblTaxIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("<html>\n<center>\n<div>MENU DE COBRO DE</div>\n<div>IMPUESTO VEHICULAR</div>\n</center>\n</html>");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(jpVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213)
                        .addComponent(jpPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(292, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jpVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Evento que se activa al iniciar la ventana/frame
    // Setea la data del usuario en los labels del lado izquierdo de la ventana
    private void AbrirFrameEvento(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_AbrirFrameEvento
        graphicsLabels();
        lblUsuario.setText(propietario.getNombre());
        lblCedula.setText(propietario.getCedula());
        lblLicencia.setText(propietario.getLicencia());
    }//GEN-LAST:event_AbrirFrameEvento

    /**
     * Establece las imagenes en los labels haciendo uso de la dependencia
     * RSScaleLabel
     */
    public void graphicsLabels() {
        // Añade las imagenes del panel lateral izquiero
        lblProfileIcon.setText("");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblProfileIcon, "src/multimedia/user.png");
        jLabel5.setText("");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel5, "src/multimedia/power.png");
        jLabel10.setText("");
        rsscalelabel.RSScaleLabel.setScaleLabel(jLabel10, "src/multimedia/cerrar-sesion.png");

        // Añade las imagenes del menu principal (menus para ser exactos)
        lblCarIcon.setText("");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblCarIcon, "src/multimedia/carIcon.png");
        lblTaxIcon.setText("");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblTaxIcon, "src/multimedia/taxIcon.png");
        //lblFacturaIcon.setText("");
        //rsscalelabel.RSScaleLabel.setScaleLabel(lblFacturaIcon, "src/multimedia/factura.png");
        lblConfigIcon.setText("");
        rsscalelabel.RSScaleLabel.setScaleLabel(lblConfigIcon, "src/multimedia/configIcon.png");
    }

    private void btnCerrarEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarEvento
        this.dispose();
        System.exit(0);
        System.out.println("Programa finalizado.");
    }//GEN-LAST:event_btnCerrarEvento

    private void jpVehiculoHoverEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVehiculoHoverEvento
        jpVehiculo.setBackground(Color.LIGHT_GRAY);
        jLabel6.setForeground(Color.white);
    }//GEN-LAST:event_jpVehiculoHoverEvento

    private void jpVehiculoExitEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpVehiculoExitEvento
        jpVehiculo.setBackground(Color.WHITE);
        jLabel6.setForeground(Color.black);
    }//GEN-LAST:event_jpVehiculoExitEvento

    private void jpPagoHoverEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPagoHoverEvento
        jpPago.setBackground(Color.LIGHT_GRAY);
        jLabel7.setForeground(Color.white);
    }//GEN-LAST:event_jpPagoHoverEvento

    private void jpPagoExitEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPagoExitEvento
        jpPago.setBackground(Color.WHITE);
        jLabel7.setForeground(Color.black);
    }//GEN-LAST:event_jpPagoExitEvento

    private void jpConfiguracionHoverEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpConfiguracionHoverEvento
        jpConfiguracion.setBackground(Color.LIGHT_GRAY);
        jLabel9.setForeground(Color.white);
    }//GEN-LAST:event_jpConfiguracionHoverEvento

    private void jpConfiguracionExitEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpConfiguracionExitEvento
        jpConfiguracion.setBackground(Color.WHITE);
        jLabel9.setForeground(Color.black);
    }//GEN-LAST:event_jpConfiguracionExitEvento

    /**
     * @param evt Abre el dialog de menus vehiculos
     */
    private void btnVehiculoEventoClic(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculoEventoClic
        DVehiculo dv = new DVehiculo(this, rootPaneCheckingEnabled);
        dv.setLocationRelativeTo(this);
        dv.setPropietario(propietario);
        dv.setVisible(true);
    }//GEN-LAST:event_btnVehiculoEventoClic

    /**
     * @param evt Evento del clic al boton Valida si la cuenta posee carros, de
     * ser asi le permite hacer el pago Si no cuenta con carros le niega el
     * acceso
     */
    private void jpPagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpPagoMouseClicked
        int contador = 0;
        DPagoFactura dpf = new DPagoFactura(this, rootPaneCheckingEnabled);
        ArrayList<Vehiculo> vehiculos = control.listaVehiculos(this.propietario.getId_propietario());
        for (Vehiculo vehiculo : vehiculos) {
            if (vehiculo.getEstado() == true) {
                contador++;
            }
        }

        if (contador > 0) {
            dpf.setPropietario(propietario);
            dpf.setLocationRelativeTo(this);
            dpf.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No tienes vehiculos que puedas pagar.");
        }
    }//GEN-LAST:event_jpPagoMouseClicked

    /**
     * @param evt Cierra la cuenta actual y envia al usuario a la pantalla de
     * inicio de sesion
     */
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        FAcceso fac = new FAcceso();
        this.setVisible(false);
        fac.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jpConfiguracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpConfiguracionMouseClicked
        DAjustePerfil dap = new DAjustePerfil(this, rootPaneCheckingEnabled);
        dap.setLocationRelativeTo(this);
        dap.setPropietario(propietario);
        dap.setVisible(true);
    }//GEN-LAST:event_jpConfiguracionMouseClicked

    // Envia los datos del propietarios al dialog
    public void setPropietario(Propietario propietario) {
        this.propietario = propietario;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel jpConfiguracion;
    private javax.swing.JPanel jpPago;
    private javax.swing.JPanel jpVehiculo;
    private javax.swing.JLabel lblCarIcon;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblConfigIcon;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JLabel lblProfileIcon;
    private javax.swing.JLabel lblTaxIcon;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
