package vistas;

import modelos.Propietario;
import servicios.Control;
import vistas.vehiculo.DAgregarVehiculo;
import vistas.vehiculo.DEliminarVehiculo;
import vistas.vehiculo.DListarVehiculo;
import vistas.vehiculo.DModificarVehiculo;

/**
 *
 * @author josef
 */
public class DMenuVehiculo extends javax.swing.JDialog {

    public Propietario propietario = new Propietario();
    Control control = new Control();
    
    /**
     * Creates new form DMenuVehiculo
     */
    public DMenuVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnListar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Vehicular");

        btnListar.setText("Mis Vehiculos");
        btnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnListarClickEvento(evt);
            }
        });

        btnAgregar.setText("Agregar Vehiculos");
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AgregarVehiculoClickEvento(evt);
            }
        });

        btnModificar.setText("Modificar Vehiculo");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarClickEvento(evt);
            }
        });

        btnEliminar.setText("Eliminar Vehiculo");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarVehiculoClickEvento(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Boton que envia al frame de que lista los vehiculos del usuario 
    private void btnListarClickEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnListarClickEvento
        FPrincipal fprincipal = new FPrincipal();
        DListarVehiculo dlv = new DListarVehiculo(fprincipal, true);
        dlv.setPropietario(propietario);
        this.setVisible(false);
        dlv.setVisible(true);
    }//GEN-LAST:event_btnListarClickEvento
    //Boton que envia al frame de elimina el vehiculo 
    private void btnEliminarVehiculoClickEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarVehiculoClickEvento
        FPrincipal fp = new FPrincipal();
        DEliminarVehiculo dev = new DEliminarVehiculo(fp, true);
        dev.setPropietario(propietario);
        this.setVisible(false);
        dev.setVisible(true);
    }//GEN-LAST:event_btnEliminarVehiculoClickEvento
    //BOTON QUE ENVIA AL FRAME DE ACTUALIZAR VEHICULO
    private void btnModificarClickEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarClickEvento
        FPrincipal fp = new FPrincipal();
        DModificarVehiculo dmv = new DModificarVehiculo(fp, true);
        dmv.setPropietario(propietario);
        this.setVisible(false);
        dmv.setVisible(true);
    }//GEN-LAST:event_btnModificarClickEvento
    //Boton que envia al frame de agregar vehiculo
    private void AgregarVehiculoClickEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarVehiculoClickEvento
        FPrincipal fp = new FPrincipal();
        DAgregarVehiculo dav = new DAgregarVehiculo(fp, true);
        dav.setPropietario(propietario);
        this.setVisible(false);
        dav.setVisible(true);
    }//GEN-LAST:event_AgregarVehiculoClickEvento
    
    public void setPropietario(Propietario propietario){
        this.propietario = propietario;
    }
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DMenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DMenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DMenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DMenuVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DMenuVehiculo dialog = new DMenuVehiculo(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
