package vistas.vehiculo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import modelos.Propietario;
import modelos.Vehiculo;
import servicios.Control;

/**
 *
 * @author josef
 * FRAME para la eliminacion de vehiculo del propietario
 */
public class DEliminarVehiculo extends javax.swing.JDialog {
    //Creacion de objetos para la clase
    public Propietario propietario = new Propietario();
    Control control = new Control();
    ArrayList<Vehiculo> listaVehiculo = new ArrayList<>();
    DefaultTableModel dtmVehiculos = new DefaultTableModel();
    JTableHeader tableHeader;
    TableModel modeloTabla;
    DefaultTableModel model;
    
    /**
     * Creates new form DEliminarVehiculo
     */
    //Metodo de Eliminacion de vehiculo
    public DEliminarVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setModelo();
        this.model = (DefaultTableModel) JTVehiculos.getModel();
        this.modeloTabla = JTVehiculos.getModel();
        this.tableHeader = JTVehiculos.getTableHeader();
        tableHeader.setReorderingAllowed(false);
    }
    //Metodo de setea la variable propietario de otra clase 
    public void setPropietario(Propietario propietario){
        this.propietario = propietario;
        llamarTabla();
    }
    //Metodo que trae la tabla, se utiliza para altualizar la lista
    public void llamarTabla(){
        listaVehiculo = control.listaVehiculos(this.propietario.getId_propietario());
        setearTable();
    }
    //Metodo que setea la cabecera de la tabla
    public void setModelo(){
        String[] cabecera = {"N°", "Marca", "Modelo", "Año", "Placa", "Color"};
        dtmVehiculos.setColumnIdentifiers(cabecera);
        JTVehiculos.setModel(dtmVehiculos);
    }
    //Metodo que llena la tabla 
    public void setearTable(){
        Object[] datos = new Object[dtmVehiculos.getColumnCount()];
        int i = 1;
        dtmVehiculos.setRowCount(0);
        for(Vehiculo vehiculo : listaVehiculo){
            if(vehiculo.getEstado() == true){
                datos[0] = i;
                datos[1] = vehiculo.getMarca();
                datos[2] = vehiculo.getModelo();
                datos[3] = vehiculo.getAnio();
                datos[4] = vehiculo.getPlaca();
                datos[5] = vehiculo.getColor();
                i++;
                dtmVehiculos.addRow(datos);
            }
        }
        JTVehiculos.setModel(dtmVehiculos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTVehiculos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(801, 401));

        jLabel1.setText("ELIMINAR VEHICULO");

        JTVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(JTVehiculos);

        jButton1.setText("Eliminar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarClickEvento(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(313, 313, 313))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(336, 336, 336))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Boton que elimina el vehiculo seleccionado 
    private void btnEliminarClickEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarClickEvento
        String placa = "";
        
        int fila = JTVehiculos.getSelectedRow();
        //int columna = JTVehiculos.getSelectedColumn();
        
        placa = (String) modeloTabla.getValueAt(fila, 4);
        
        if(control.eliminarVehiculo(placa)){
            JOptionPane.showMessageDialog(null, "Vehiculo eliminado exitosamente!");
        } else {
            JOptionPane.showMessageDialog(null, "El vehiculo no ha podido ser eliminado.");
        }
        
        model.setRowCount(0);
        llamarTabla();
    }//GEN-LAST:event_btnEliminarClickEvento

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DEliminarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DEliminarVehiculo dialog = new DEliminarVehiculo(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTVehiculos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
