package vistas.vehiculo;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
import modelos.Propietario;
import modelos.Vehiculo;
import servicios.Control;

/**
 *
 * @author josef
 * Frame para actualizar los datos de vehiculo del propietario
 */
public class DModificarVehiculo extends javax.swing.JDialog {
    //Creacion de instacias (Objetos) y creacion de listas a utilizar 
    public Propietario propietario = new Propietario();
    ArrayList<String> colores = new ArrayList<String>();
    Control control = new Control();
    ArrayList<Vehiculo> listaVehiculo = new ArrayList<>();
    DefaultTableModel dtmVehiculos = new DefaultTableModel();
    JTableHeader tableHeader;
    TableModel modeloTabla;
    DefaultTableModel model;
    
    /**
     * Creates new form DModificarVehiculo
     */
    public DModificarVehiculo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setModelo();
        this.model = (DefaultTableModel) JTVehiculos.getModel();
        this.modeloTabla = JTVehiculos.getModel();
        this.tableHeader = JTVehiculos.getTableHeader();
        tableHeader.setReorderingAllowed(false);
        setColores();
    }

    public void setPropietario(Propietario propietario){
        this.propietario = propietario;
        llamarTable();
    }
    //Metodo que consulta la tabla
    public void llamarTable() {
        listaVehiculo = control.listaVehiculos(this.propietario.getId_propietario());
        setearTable();        
    }
    //Metodo que actualiza la tabla modelo
    public void setModelo(){
        String[] cabecera = {"N°", "Marca", "Modelo", "Año", "Placa", "Color"};
        dtmVehiculos.setColumnIdentifiers(cabecera);
        JTVehiculos.setModel(dtmVehiculos);
    }
    //Metodo que actualiza la tabla
    public void setearTable(){
        Object[] datos = new Object[dtmVehiculos.getColumnCount()];
        int i = 1;
        dtmVehiculos.setRowCount(0);
        for(Vehiculo vehiculo : listaVehiculo){
            if(vehiculo.getEstado() == true){
                datos[0] = i;
                datos[1] = vehiculo.getMarca();
                datos[2] = vehiculo.getModelo();
                datos[3] = vehiculo.getAnio();
                datos[4] = vehiculo.getPlaca();
                datos[5] = vehiculo.getColor();
                i++;
                dtmVehiculos.addRow(datos);
            }
        }
        JTVehiculos.setModel(dtmVehiculos);
    }
    //Metodo que actualizacolores y los agrega al ComboBox 
    public void setColores(){
        colores.add("Negro");
        colores.add("Blanco");
        colores.add("Gris");
        colores.add("Rojo");
        colores.add("Azul");
        colores.add("Plateado");
        colores.add("Dorado");
        colores.add("Beige");
        colores.add("Marron");
        colores.add("Verde");
        
        CBColor.addItem("Seleccionar");
        for(int i = 0; i < colores.size(); i++){
            CBColor.addItem(colores.get(i));
        }

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTVehiculos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        CBColor = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("MODIFICAR AUTO");

        JTVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        JTVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarClickEvento(evt);
            }
        });
        jScrollPane2.setViewportView(JTVehiculos);

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Año");

        jLabel5.setText("Placa");

        lblMarca.setText("${lblMarca}");

        lblModelo.setText("${lblModelo}");

        lblPlaca.setText("${lblPlaca}");

        lblAnio.setText("${lblAnio}");

        jLabel6.setText("Color");

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarClickEvento(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMarca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModelo, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblAnio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblPlaca, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(CBColor, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblMarca)
                    .addComponent(jLabel4)
                    .addComponent(lblAnio))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lblModelo)
                    .addComponent(lblPlaca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(btnModificar)
                    .addComponent(CBColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Evento que actualiza el Combo box de Modelos de Marca
    private void ModificarClickEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarClickEvento
        int fila = JTVehiculos.getSelectedRow();
        
        lblMarca.setText((String) modeloTabla.getValueAt(fila, 1));
        lblModelo.setText((String) modeloTabla.getValueAt(fila, 2));
        lblAnio.setText((String) modeloTabla.getValueAt(fila, 3));
        lblPlaca.setText((String) modeloTabla.getValueAt(fila, 4));    
        
        CBColor.setSelectedItem((String) modeloTabla.getValueAt(fila, 5));
    }//GEN-LAST:event_ModificarClickEvento
    //Boton que actualiza los datos si cambiaron en el fram de Modificar
    //vehiculo
    private void btnModificarClickEvento(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarClickEvento
        try {
            int fila = JTVehiculos.getSelectedRow();
            if(fila != -1){
                if(CBColor.getSelectedItem().toString().equalsIgnoreCase((String) modeloTabla.getValueAt(fila, 5)) 
                        || CBColor.getSelectedItem().toString().equalsIgnoreCase("Seleccionar")){
                    JOptionPane.showMessageDialog(null, "Escoge otro color para poder modificar.");
                } else {
                    control.modificarVehiculo(CBColor.getSelectedItem().toString(), (String) modeloTabla.getValueAt(fila, 4));
                    JOptionPane.showMessageDialog(null, "Actualizado correctamente.");
                    llamarTable();
                    model.setRowCount(0);
                    setearTable();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Selecciona el auto que quieres modificar.");
            }
        } catch(Exception ex){
            System.out.println("Ha ocurrido un error. " + ex.getMessage());
        }
    }//GEN-LAST:event_btnModificarClickEvento

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DModificarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DModificarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DModificarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DModificarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                DModificarVehiculo dialog = new DModificarVehiculo(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBColor;
    private javax.swing.JTable JTVehiculos;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblPlaca;
    // End of variables declaration//GEN-END:variables
}
